add waste_collection_schedule component
home-assistant/wheels-custom-integrations pull request #384
Opened 2021-04-29 09:01 UTC by mampfes

2021-04-29 09:24 UTC, frenck commented on components/waste_collection_schedule.json
> +    "manifest": "https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/manifest.json",
```suggestion
    "manifest": "https://raw.githubusercontent.com/mampfes/hacs_waste_collection_schedule/master/custom_components/waste_collection_schedule/manifest.json",
```

2021-05-07 08:14 UTC, ludeeus requested changes

2021-05-07 08:14 UTC, ludeeus commented on components/waste_collection_schedule.json
> +    "manifest": "https://raw.githubusercontent.com/mampfes/hacs_waste_collection_schedule/master/custom_components/waste_collection_schedule/manifest.json",
The documentation URL in the manifest file is not correct.

> "documentation": "https://www.home-assistant.io/integrations/waste_collection_schedule",

2021-05-14 07:46 UTC, ludeeus approved these changes

2021-05-14 07:46 UTC, merged